### ISSUE TITLE
Support for multiple lines with same NodeName in gres.conf

### ISSUE THREAD

**Issue by dsloanm** [charmed-hpc/slurmutils#39]
### Bug Description

`gresconfig` seems to assume one `NodeName` line per node, limiting configuration options.

### To Reproduce

Attempting to use two `NodeName` entries in `gres.conf` to configure a node `juju-abc654-1` with two distinct types of GPU. Desired state of `gres.conf`:

```
NodeName=juju-abc654-1 Name=gpu Type=tesla_t4 File=/dev/nvidia[0-1]
NodeName=juju-abc654-1 Name=gpu Type=l40s File=/dev/nvidia[2-3]
```

with `slurmutils`:

```python3
from slurmutils.editors import gresconfig
from slurmutils.models import GRESNode

with gresconfig.edit("gres.conf") as config:
    node = GRESNode(
        NodeName="juju-abc654-1",
        Name="gpu",
        Type="tesla_t4",
        File="/dev/nvidia[0-1]",
    )
    node2 = GRESNode(
        NodeName="juju-abc654-1",
        Name="gpu",
        Type="l40s",
        File="/dev/nvidia[2-3]",
    )
    
    config.nodes.update(node.dict())
    # How is node2 added?
```

Edit: further reproducer, using existing `gres.conf` in desired state:

```python3
from slurmutils.editors import gresconfig
from slurmutils.models import GRESNode

with gresconfig.edit("gres.conf") as config:
    print(config.nodes)
```

returns `{'juju-abc654-1': {'Name': 'gpu', 'Type': 'l40s', 'File': '/dev/nvidia[2-3]'}}`, without the `tesla_t4` entry. 

### Environment

Running locally with the latest main commit: https://github.com/charmed-hpc/slurmutils/commit/60bc8e617d4745773995ea55288851bdee28ad6e.

### Relevant log output

```shell
N/A
```

**Comment by NucciTheBoss** [comment]
It shouldn't be too difficult to update the `names` pocket on the `GRESConfig` data model in practice.

However, what I'm wondering is if this is valid configuration syntax in _gres.conf_? @dsloanm have you been able to verify that these lines in _gres.conf_ don't overwrite each other in Slurm itself 🤔

**Comment by NucciTheBoss** [comment]
Thanks for sharing that mailing list thread. It will help with developing the complimenting unit tests!
